// Code generated by internal/consts/generate.go. DO NOT EDIT.

package consts

//go:generate go run generate.go
const (
	// DbusName owned by the broker for authd to contact us.
	DbusName = "com.ubuntu.authd.Oidc"
	// DbusObject main object path for authd to contact us.
	DbusObject = "/com/ubuntu/authd/Oidc"
)
