name: Set up SSH keys for VM provisioning
description: "Sets up SSH keys for VM provisioning"
inputs:
  E2E_VM_SSH_PRIV_KEY:
    description: "Private SSH key for VM provisioning"
    required: true
  E2E_VM_SSH_PUB_KEY:
    description: "Public SSH key for VM provisioning"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Set up SSH keys for the VM provisioning
      shell: bash
      run: |
        set -eu

        mkdir -p /home/runner/.ssh
        chmod 700 /home/runner/.ssh

        echo "${{ inputs.E2E_VM_SSH_PRIV_KEY }}" > /home/runner/.ssh/id_rsa
        chmod 600 /home/runner/.ssh/id_rsa

        echo "${{ inputs.E2E_VM_SSH_PUB_KEY }}" > /home/runner/.ssh/id_rsa.pub
        chmod 644 /home/runner/.ssh/id_rsa.pub

        eval "$(ssh-agent -s)"

        ssh-add /home/runner/.ssh/id_rsa
