name: authd-google
summary: Google Broker for authd
description: |
  Broker that enables OIDC authentication with Google for authd.
adopt-info: version
grade: stable
base: core24
confinement: strict
license: GPL-3.0

apps:
  authd-google:
    command: bin/authd-google
    daemon: simple
    slots:
      - dbus-authd
    plugs:
      - network
    restart-condition: always

slots:
  dbus-authd:
    interface: dbus
    bus: system
    name: com.ubuntu.authd.Google

parts:
  broker:
    source: .
    source-type: local
    plugin: go
    go-buildtags: [withgoogle]
    build-snaps:
      - go
    override-build: |
      go mod download all
      go build -tags=withgoogle -o ${GOBIN}/authd-google ./cmd/authd-oidc
  config:
    source: conf/
    source-type: local
    plugin: dump
    organize:
      "authd.conf": "conf/authd/google.conf"
      "broker.conf": "conf/broker.conf.orig"
      "migrations": "conf/migrations"
  # SemVer comparison helper
  semver:
    source: tools
    source-type: local
    plugin: go
    override-build: |
      go mod download all
      go build -o ${GOBIN}/semver semver/semver.go
  # Build the snap version from the git repository and current tree state.
  version:
    source: .
    plugin: nil
    build-packages:
      - git # The script needs Git.
    override-build: ./snap/get_version
    after:
      - semver
