name: authd-oidc
summary: OIDC Broker for authd
description: |
  Broker that enables OIDC authentication for authd.
adopt-info: version
grade: stable
base: core24
confinement: strict
license: GPL-3.0

apps:
  authd-oidc:
    command: bin/authd-oidc
    daemon: dbus
    slots:
      - dbus-authd
    plugs:
      - network
    restart-condition: always
    activates-on: [dbus-authd]

slots:
  dbus-authd:
    interface: dbus
    bus: system
    name: com.ubuntu.authd.Oidc

parts:
  broker:
    source: .
    source-type: local
    plugin: go
    build-snaps:
      - go
  config:
    source: conf/
    source-type: local
    plugin: dump
    organize:
      "authd.conf": "conf/authd/oidc.conf"
      "broker.conf": "conf/broker.conf.orig"
      "migrations": "conf/migrations"
  # SemVer comparison helper
  semver:
    source: tools
    source-type: local
    plugin: go
    override-build: |
      go mod download all
      go mod vendor
      go build -o ${GOBIN}/semver semver/semver.go
  # Build the snap version from the git repository and current tree state.
  version:
    source: .
    plugin: nil
    build-packages:
      - git # The script needs Git.
    override-build: |
      craftctl set version="$(./snap/version)"
    after:
      - semver
