name: Build and Cache Ubuntu VM

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight

env:
  DEBIAN_FRONTEND: noninteractive
  apt_dependencies: >-
    bsdutils
    cloud-image-utils
    libvirt0
    libvirt-clients
    libvirt-clients-qemu
    libvirt-daemon
    libvirt-daemon-driver-qemu
    libvirt-daemon-system
    qemu-kvm
    qemu-system-x86
    qemu-utils
    sshpass
    wget
    xvfb

jobs:
  build-vm:
    name: Provision and cache Ubuntu VM for the E2E tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Even though we already try installing the dependencies in the provisioning
      # script, we need to install them here to ensure that we can add the user
      # to the libvirt group
      - name: Install APT dependencies
        run: |
          set -eu
          sudo apt-get update
          sudo apt-get -y install ${{ env.apt_dependencies }}

          # Add the current user to the libvirt group to be able to use libvirt
          sudo usermod -aG libvirt $USER
          exec newgrp libvirt

      - name: Set up SSH keys for the VM provisioning
        run: |
          set -eu

          mkdir -p ~/.ssh

          echo "${{ secrets.E2E_VM_SSH_PRIV_KEY }}" > ~/.ssh/e2e_vm_key
          chmod 600 ~/.ssh/e2e_vm_key

          echo "${{ secrets.E2E_VM_SSH_PUB_KEY }}" > ~/.ssh/e2e_vm_key.pub
          chmod 644 ~/.ssh/e2e_vm_key.pub

      - name: Provision the base E2E Ubuntu VM
        id: provision-vm
        run: |
          set -eu

          ./e2e-tests/vm/provision-ubuntu.sh -k ~/.ssh/e2e_vm_key.pub

      - name: Clean previous cache
        if: always() && steps.provision-vm.outcome == 'success'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          set -eu

          gh cache delete e2e-runner-vm || true
          echo "Previous cache (if any) deleted"

      - name: Cache the VM image
        uses: actions/cache/save@v4
        if: always() && steps.provision-vm.outcome == 'success'
        with:
          path: ./e2e-tests/vm/.artifacts/e2e-runner.qcow2
          key: e2e-runner-vm
