#!/bin/sh
set -eu

snap_base_dir=$(dirname ${SNAP})

cat <<EOF > ${SNAP_COMMON}/oidc-broker
[authd]
name = OIDC Broker
brand_icon = ${snap_base_dir}/current/broker_icon.png
dbus_name = com.ubuntu.authd.OidcBroker
dbus_object = /com/ubuntu/authd/OidcBroker

[oidc]
issuer = https://{issuer_url}
client_id = {client_id}

# The amount of days the user will be allowed to authenticate without a network connection.
# offline_expiration = 180

# The directory where the user's home directory will be created.
# The user home directory will be created in the format of {home_base_dir}/{username}
# home_base_dir = /home

EOF
