#!/bin/sh
set -eu

snap_base_dir=$(dirname ${SNAP})

cat <<EOF > ${SNAP_COMMON}/oidc
[authd]
# This section is used by authd to identify and communicate with the broker.
# It should not be edited.
name = OIDC
brand_icon = ${snap_base_dir}/current/broker_icon.png
dbus_name = com.ubuntu.authd.Oidc
dbus_object = /com/ubuntu/authd/Oidc

[oidc]
issuer = https://{issuer_url}
client_id = {client_id}

# The directory where the home directory will be created for new users.
# Existing users will keep their current directory.
# The user home directory will be created in the format of {home_base_dir}/{username}
# home_base_dir = /home

# The username suffixes that are allowed to login via ssh without existing previously in the system.
# The suffixes must be separated by commas.
# ssh_allowed_suffixes = @example.com,@anotherexample.com

EOF
